# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
    ports:
      - 5432:5432
